-- Production well controls (all start producing at day 1)

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	688.4345187655468	/
/

 
TSTEP
 1 /--1 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--2 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--3 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1496.5967799251018	/
/

 
TSTEP
 1 /--4 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	259.410108520351	/
/

 
TSTEP
 1 /--5 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	29.931935598502037	/
/

 
TSTEP
 1 /--6 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	179.59161359101222	/
/

 
TSTEP
 1 /--7 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1077.5496815460733	/
/

 
TSTEP
 1 /--8 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--9 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--10 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--11 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--12 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--13 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--14 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1596.3698985867754	/
/

 
TSTEP
 1 /--15 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1346.9371019325918	/
/

 
TSTEP
 1 /--16 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1057.5950578137388	/
/

 
TSTEP
 1 /--17 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--18 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--19 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--20 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--21 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--22 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--23 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--24 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	578.6840882377061	/
/

 
TSTEP
 1 /--25 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1356.9144137987591	/
/

 
TSTEP
 1 /--26 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1287.0732307355877	/
/

 
TSTEP
 1 /--27 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--28 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--29 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--30 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--31 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--32 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--33 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	79.81849492933877	/
/

 
TSTEP
 1 /--34 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1486.6194680589344	/
/

 
TSTEP
 1 /--35 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--36 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--37 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1167.3454883415795	/
/

 
TSTEP
 1 /--38 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--39 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--40 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--41 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--42 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1426.7555968619304	/
/

 
TSTEP
 1 /--43 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	897.9580679550611	/
/

 
TSTEP
 1 /--44 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	409.0697865128612	/
/

 
TSTEP
 1 /--45 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1336.9597900664244	/
/

 
TSTEP
 1 /--46 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1406.8009731295958	/
/

 
TSTEP
 1 /--47 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	568.7067763715387	/
/

 
TSTEP
 1 /--48 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	369.1605390481918	/
/

 
TSTEP
 1 /--49 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	349.2059153158571	/
/

 
TSTEP
 1 /--50 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	768.2530136948857	/
/

 
TSTEP
 1 /--51 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	269.38742038651833	/
/

 
TSTEP
 1 /--52 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--53 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	89.79580679550611	/
/

 
TSTEP
 1 /--54 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	309.29666785118775	/
/

 
TSTEP
 1 /--55 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--56 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--57 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	947.8446272858979	/
/

 
TSTEP
 1 /--58 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--59 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1596.3698985867754	/
/

 
TSTEP
 1 /--60 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--61 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	838.094196758057	/
/

 
TSTEP
 1 /--62 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--63 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	99.77311866167346	/
/

 
TSTEP
 1 /--64 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	578.6840882377061	/
/

 
TSTEP
 1 /--65 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	259.410108520351	/
/

 
TSTEP
 1 /--66 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	478.9109695760326	/
/

 
TSTEP
 1 /--67 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	458.95634584369793	/
/

 
TSTEP
 1 /--68 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1237.186671404751	/
/

 
TSTEP
 1 /--69 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	9.977311866167346	/
/

 
TSTEP
 1 /--70 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	209.52354918951426	/
/

 
TSTEP
 1 /--71 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	768.2530136948857	/
/

 
TSTEP
 1 /--72 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	229.47817292184897	/
/

 
TSTEP
 1 /--73 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--74 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--75 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1227.2093595385836	/
/

 
TSTEP
 1 /--76 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--77 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--78 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--79 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	957.8219391520652	/
/

 
TSTEP
 1 /--80 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1137.4135527430774	/
/

 
TSTEP
 1 /--81 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	89.79580679550611	/
/

 
TSTEP
 1 /--82 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	289.34204411885304	/
/

 
TSTEP
 1 /--83 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	419.0470983790285	/
/

 
TSTEP
 1 /--84 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	139.68236612634286	/
/

 
TSTEP
 1 /--85 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	109.7504305278408	/
/

 
TSTEP
 1 /--86 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	967.7992510182326	/
/

 
TSTEP
 1 /--87 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1117.4589290107428	/
/

 
TSTEP
 1 /--88 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1237.186671404751	/
/

 
TSTEP
 1 /--89 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	349.2059153158571	/
/

 
TSTEP
 1 /--90 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	259.410108520351	/
/

 
TSTEP
 1 /--91 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	688.4345187655468	/
/

 
TSTEP
 1 /--92 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--93 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--94 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	389.1151627805265	/
/

 
TSTEP
 1 /--95 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	788.2076374272203	/
/

 
TSTEP
 1 /--96 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	409.0697865128612	/
/

 
TSTEP
 1 /--97 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	159.63698985867754	/
/

 
TSTEP
 1 /--98 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	189.56892545717957	/
/

 
TSTEP
 1 /--99 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	488.88828144219997	/
/

 
TSTEP
 1 /--100 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	339.2286034496898	/
/

 
TSTEP
 1 /--101 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	927.8900035535631	/
/

 
TSTEP
 1 /--102 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	907.9353798212285	/
/

 
TSTEP
 1 /--103 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--104 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--105 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1257.1412951370855	/
/

 
TSTEP
 1 /--106 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	628.5706475685428	/
/

 
TSTEP
 1 /--107 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	359.18322718202444	/
/

 
TSTEP
 1 /--108 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1366.8917256649263	/
/

 
TSTEP
 1 /--109 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	19.954623732334692	/
/

 
TSTEP
 1 /--110 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	159.63698985867754	/
/

 
TSTEP
 1 /--111 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--112 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--113 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1007.708498482902	/
/

 
TSTEP
 1 /--114 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1506.5740917912692	/
/

 
TSTEP
 1 /--115 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--116 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1566.4379629882733	/
/

 
TSTEP
 1 /--117 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	269.38742038651833	/
/

 
TSTEP
 1 /--118 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	838.094196758057	/
/

 
TSTEP
 1 /--119 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	718.3664543640489	/
/

 
TSTEP
 1 /--120 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1207.2547358062488	/
/

 
TSTEP
 1 /--121 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	508.8429051745346	/
/

 
TSTEP
 1 /--122 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1057.5950578137388	/
/

 
TSTEP
 1 /--123 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	558.7294645053714	/
/

 
TSTEP
 1 /--124 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	429.0244102451959	/
/

 
TSTEP
 1 /--125 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	578.6840882377061	/
/

 
TSTEP
 1 /--126 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	159.63698985867754	/
/

 
TSTEP
 1 /--127 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	608.6160238362081	/
/

 
TSTEP
 1 /--128 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	518.820217040702	/
/

 
TSTEP
 1 /--129 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	79.81849492933877	/
/

 
TSTEP
 1 /--130 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	488.88828144219997	/
/

 
TSTEP
 1 /--131 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--132 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1317.0051663340896	/
/

 
TSTEP
 1 /--133 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--134 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	788.2076374272203	/
/

 
TSTEP
 1 /--135 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--136 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--137 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	768.2530136948857	/
/

 
TSTEP
 1 /--138 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	289.34204411885304	/
/

 
TSTEP
 1 /--139 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	319.2739797173551	/
/

 
TSTEP
 1 /--140 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	209.52354918951426	/
/

 
TSTEP
 1 /--141 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	389.1151627805265	/
/

 
TSTEP
 1 /--142 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	458.95634584369793	/
/

 
TSTEP
 1 /--143 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	89.79580679550611	/
/

 
TSTEP
 1 /--144 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	99.77311866167346	/
/

 
TSTEP
 1 /--145 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	309.29666785118775	/
/

 
TSTEP
 1 /--146 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--147 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1616.32452231911	/
/

 
TSTEP
 1 /--148 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	748.2983899625509	/
/

 
TSTEP
 1 /--149 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1376.8690375310937	/
/

 
TSTEP
 1 /--150 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1117.4589290107428	/
/

 
TSTEP
 1 /--151 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	389.1151627805265	/
/

 
TSTEP
 1 /--152 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--153 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--154 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--155 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	109.7504305278408	/
/

 
TSTEP
 1 /--156 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	189.56892545717957	/
/

 
TSTEP
 1 /--157 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	648.5252713008775	/
/

 
TSTEP
 1 /--158 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--159 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--160 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	399.09247464669386	/
/

 
TSTEP
 1 /--161 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	329.2512915835224	/
/

 
TSTEP
 1 /--162 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	89.79580679550611	/
/

 
TSTEP
 1 /--163 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--164 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--165 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--166 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1207.2547358062488	/
/

 
TSTEP
 1 /--167 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	199.54623732334693	/
/

 
TSTEP
 1 /--168 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	219.5008610556816	/
/

 
TSTEP
 1 /--169 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	239.4554847880163	/
/

 
TSTEP
 1 /--170 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	109.7504305278408	/
/

 
TSTEP
 1 /--171 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	538.7748407730367	/
/

 
TSTEP
 1 /--172 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	39.909247464669384	/
/

 
TSTEP
 1 /--173 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1127.43624087691	/
/

 
TSTEP
 1 /--174 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	189.56892545717957	/
/

 
TSTEP
 1 /--175 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	389.1151627805265	/
/

 
TSTEP
 1 /--176 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	59.86387119700407	/
/

 
TSTEP
 1 /--177 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	359.18322718202444	/
/

 
TSTEP
 1 /--178 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--179 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--180 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	99.77311866167346	/
/

 
TSTEP
 1 /--181 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--182 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	249.43279665418365	/
/

 
TSTEP
 1 /--183 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--184 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	329.2512915835224	/
/

 
TSTEP
 1 /--185 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	109.7504305278408	/
/

 
TSTEP
 1 /--186 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	369.1605390481918	/
/

 
TSTEP
 1 /--187 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	89.79580679550611	/
/

 
TSTEP
 1 /--188 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--189 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	229.47817292184897	/
/

 
TSTEP
 1 /--190 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1646.2564579176121	/
/

 
TSTEP
 1 /--191 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1416.7782849957632	/
/

 
TSTEP
 1 /--192 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--193 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--194 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--195 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1097.504305278408	/
/

 
TSTEP
 1 /--196 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1067.572369679906	/
/

 
TSTEP
 1 /--197 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--198 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	99.77311866167346	/
/

 
TSTEP
 1 /--199 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	967.7992510182326	/
/

 
TSTEP
 1 /--200 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1606.3472104529428	/
/

 
TSTEP
 1 /--201 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	588.6614001038735	/
/

 
TSTEP
 1 /--202 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--203 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	219.5008610556816	/
/

 
TSTEP
 1 /--204 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	49.88655933083673	/
/

 
TSTEP
 1 /--205 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--206 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--207 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	0.0	/
/

 
TSTEP
 1 /--208 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	159.63698985867754	/
/

 
TSTEP
 1 /--209 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1177.322800207747	/
/

 
TSTEP
 1 /--210 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	209.52354918951426	/
/

 
TSTEP
 1 /--211 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	468.93365770986526	/
/

 
TSTEP
 1 /--212 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	79.81849492933877	/
/

 
TSTEP
 1 /--213 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	269.38742038651833	/
/

 
TSTEP
 1 /--214 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	219.5008610556816	/
/

 
TSTEP
 1 /--215 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	339.2286034496898	/
/

 
TSTEP
 1 /--216 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	39.909247464669384	/
/

 
TSTEP
 1 /--217 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	987.7538747505672	/
/

 
TSTEP
 1 /--218 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	878.0034442227264	/
/

 
TSTEP
 1 /--219 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	738.3210780963836	/
/

 
TSTEP
 1 /--220 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	299.31935598502037	/
/

 
TSTEP
 1 /--221 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--222 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	339.2286034496898	/
/

 
TSTEP
 1 /--223 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	199.54623732334693	/
/

 
TSTEP
 1 /--224 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	937.8673154197305	/
/

 
TSTEP
 1 /--225 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--226 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--227 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	339.2286034496898	/
/

 
TSTEP
 1 /--228 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	59.86387119700407	/
/

 
TSTEP
 1 /--229 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	229.47817292184897	/
/

 
TSTEP
 1 /--230 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1376.8690375310937	/
/

 
TSTEP
 1 /--231 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	488.88828144219997	/
/

 
TSTEP
 1 /--232 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1227.2093595385836	/
/

 
TSTEP
 1 /--233 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--234 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	419.0470983790285	/
/

 
TSTEP
 1 /--235 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	49.88655933083673	/
/

 
TSTEP
 1 /--236 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	79.81849492933877	/
/

 
TSTEP
 1 /--237 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	79.81849492933877	/
/

 
TSTEP
 1 /--238 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	329.2512915835224	/
/

 
TSTEP
 1 /--239 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1117.4589290107428	/
/

 
TSTEP
 1 /--240 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1356.9144137987591	/
/

 
TSTEP
 1 /--241 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1227.2093595385836	/
/

 
TSTEP
 1 /--242 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1616.32452231911	/
/

 
TSTEP
 1 /--243 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	399.09247464669386	/
/

 
TSTEP
 1 /--244 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	329.2512915835224	/
/

 
TSTEP
 1 /--245 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	967.7992510182326	/
/

 
TSTEP
 1 /--246 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--247 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--248 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1247.1639832709182	/
/

 
TSTEP
 1 /--249 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	878.0034442227264	/
/

 
TSTEP
 1 /--250 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--251 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--252 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--253 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	688.4345187655468	/
/

 
TSTEP
 1 /--254 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1217.2320476724162	/
/

 
TSTEP
 1 /--255 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	429.0244102451959	/
/

 
TSTEP
 1 /--256 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1167.3454883415795	/
/

 
TSTEP
 1 /--257 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	379.13785091435915	/
/

 
TSTEP
 1 /--258 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	239.4554847880163	/
/

 
TSTEP
 1 /--259 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	69.84118306317143	/
/

 
TSTEP
 1 /--260 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	99.77311866167346	/
/

 
TSTEP
 1 /--261 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	89.79580679550611	/
/

 
TSTEP
 1 /--262 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--263 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--264 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	359.18322718202444	/
/

 
TSTEP
 1 /--265 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--266 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1307.0278544679222	/
/

 
TSTEP
 1 /--267 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	628.5706475685428	/
/

 
TSTEP
 1 /--268 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	169.6143017248449	/
/

 
TSTEP
 1 /--269 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	698.4118306317142	/
/

 
TSTEP
 1 /--270 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	319.2739797173551	/
/

 
TSTEP
 1 /--271 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1346.9371019325918	/
/

 
TSTEP
 1 /--272 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	419.0470983790285	/
/

 
TSTEP
 1 /--273 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1097.504305278408	/
/

 
TSTEP
 1 /--274 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--275 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--276 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	708.3891424978816	/
/

 
TSTEP
 1 /--277 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	439.0017221113632	/
/

 
TSTEP
 1 /--278 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	648.5252713008775	/
/

 
TSTEP
 1 /--279 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1057.5950578137388	/
/

 
TSTEP
 1 /--280 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--281 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	708.3891424978816	/
/

 
TSTEP
 1 /--282 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1506.5740917912692	/
/

 
TSTEP
 1 /--283 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	159.63698985867754	/
/

 
TSTEP
 1 /--284 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	169.6143017248449	/
/

 
TSTEP
 1 /--285 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--286 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--287 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--288 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--289 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1696.1430172484488	/
/

 
TSTEP
 1 /--290 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1496.5967799251018	/
/

 
TSTEP
 1 /--291 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	69.84118306317143	/
/

 
TSTEP
 1 /--292 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--293 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--294 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--295 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	369.1605390481918	/
/

 
TSTEP
 1 /--296 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	149.65967799251018	/
/

 
TSTEP
 1 /--297 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1366.8917256649263	/
/

 
TSTEP
 1 /--298 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--299 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--300 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1157.3681764754122	/
/

 
TSTEP
 1 /--301 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	269.38742038651833	/
/

 
TSTEP
 1 /--302 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1167.3454883415795	/
/

 
TSTEP
 1 /--303 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--304 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--305 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	658.5025831670448	/
/

 
TSTEP
 1 /--306 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--307 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--308 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--309 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--310 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--311 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--312 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--313 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--314 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--315 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	987.7538747505672	/
/

 
TSTEP
 1 /--316 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1257.1412951370855	/
/

 
TSTEP
 1 /--317 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--318 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--319 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1566.4379629882733	/
/

 
TSTEP
 1 /--320 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1376.8690375310937	/
/

 
TSTEP
 1 /--321 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--322 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--323 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	907.9353798212285	/
/

 
TSTEP
 1 /--324 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	518.820217040702	/
/

 
TSTEP
 1 /--325 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	69.84118306317143	/
/

 
TSTEP
 1 /--326 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	458.95634584369793	/
/

 
TSTEP
 1 /--327 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1516.5514036574366	/
/

 
TSTEP
 1 /--328 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1506.5740917912692	/
/

 
TSTEP
 1 /--329 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--330 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--331 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--332 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--333 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--334 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--335 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--336 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1366.8917256649263	/
/

 
TSTEP
 1 /--337 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	758.2757018287183	/
/

 
TSTEP
 1 /--338 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	439.0017221113632	/
/

 
TSTEP
 1 /--339 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	658.5025831670448	/
/

 
TSTEP
 1 /--340 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--341 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	828.1168848918898	/
/

 
TSTEP
 1 /--342 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--343 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--344 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--345 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--346 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--347 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--348 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--349 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1486.6194680589344	/
/

 
TSTEP
 1 /--350 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--351 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--352 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--353 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--354 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--355 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--356 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--357 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--358 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--359 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--360 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--361 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--362 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	897.9580679550611	/
/

 
TSTEP
 1 /--363 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--364 

WGRUPCON
	'INJ'	Yes 	 0 	RAT 	 1 	 / 
	'INJX'	Yes 	 0.01 	RAT 	 1 	 / 
/
GRUPTARG
	'G1'	 RATE	1726.074952846951	/
/

 
TSTEP
 1 /--365 

